spring:
    data:
      mongodb:
        uri: mongodb+srv://admin:admin123@cluster0.jiibq.mongodb.net/triviatrove?retryWrites=true&w=majority&appName=Cluster0


server:
    port: 8080
    compression:
        enabled: true
    error:
        include-message: always
    shutdown: "graceful"

data:
  initializer:
    enabled: false